In [2]:
import numpy as np

In [3]:
#Print the numpy version and the configuration
print(np.__version__)
np.show_config()

1.18.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


In [4]:
# Create a null vector of size 10
a = np.zeros(10)
print(a)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
#Create a vector with values ranging from 10 to 49
z = np.arange(10,50)
z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [6]:
#Reverse a vector (first element becomes last)
z = np.arange(50)
z = z[::-1]
print(z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [7]:
#Create a 3x3 matrix with values ranging from 0 to 8

a = np.arange(0,9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [8]:
#Create a 3x3 identity matrix
Z = np.eye(7)
print(Z)

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


In [9]:
#Create a 3x3x3 array with random values
ab = np.random.random((3,3,3))
print(ab)

[[[0.82377825 0.83482302 0.80582551]
  [0.25275719 0.06618585 0.45349722]
  [0.3268261  0.43492826 0.08129159]]

 [[0.95842464 0.79644643 0.19567435]
  [0.76755184 0.52706805 0.60263191]
  [0.01240428 0.02365279 0.43375159]]

 [[0.82957558 0.95764198 0.65718413]
  [0.53045525 0.08847209 0.91903272]
  [0.56871213 0.99180769 0.93813751]]]


In [10]:
#Create a 10x10 array with random values and find the minimum and maximum values
Z = np.random.random((3,2,7))
zmax, zmin = z.min(), z.max()
print(zmax, zmin)

0 49


In [11]:
#Standard deviation of the matrix
z = np.random.random((3,3,3))
a = np.std(Z)
print(a)

0.2809952342269608


In [12]:
#normalize any dimension matrix:value-mean/std_deviation
Z = np.random.random((5,5))
Z = (Z - np.mean(Z))/ (np.std(Z))
print(Z)

[[ 0.17735768  0.27192825  0.09428601  0.27307448 -1.55953206]
 [-1.72377701 -1.2333474  -1.21922945  1.26291244 -0.48321344]
 [ 0.60481143  0.75451686 -0.53394007  2.15387921  1.19609692]
 [ 0.47320005  1.12743993  1.22295548  0.81784795 -1.02898952]
 [-0.78450588 -1.30943822 -0.47450394  0.00847311 -0.08830281]]


In [13]:
#How to find common values between two arrays
z1 = np.random.randint(0,10,10)
print(z1)
z2 = np.random.randint(0,10,10)
print(z2)

print(np.intersect1d(z1, z2))

[5 5 7 0 2 7 9 0 9 4]
[5 1 3 4 3 0 0 7 1 4]
[0 4 5 7]


In [14]:
z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [15]:
#How to compute ((A+B)*(-A/2)) in place (without copy)
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2, out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)
print(A)

[-1.5 -1.5 -1.5]


In [16]:
z = np.random.uniform((0,10,10))
print(z)
print(z.astype(int))


[0.84146275 3.50742497 3.17131432]
[0 3 3]


In [17]:
# Create a 5x5 matrix with row values ranging from 0 to 4
Z = np.zeros((5,5))
Z+=np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [18]:
Z = np.zeros((5,5))
print(Z)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [19]:
#Create a vector of size 10 with values ranging from 0 to 1, both excluded ; endpoint is by default true but if false; last number in range excluded
z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [20]:
#How to sum a small array faster than np.sum?
z = np.random.random(10)
z.sort()
print(z)

[0.04156678 0.3396862  0.53970519 0.54358154 0.65117018 0.78347315
 0.81166601 0.902506   0.96263209 0.97623003]


In [21]:
z = np.arange(10)
print(z)


[0 1 2 3 4 5 6 7 8 9]


In [32]:
z = np.random.randint(0,2,10)
print(z)
z.sort()
print(z)

[1 1 1 1 1 1 0 1 0 1]
[0 0 1 1 1 1 1 1 1 1]


In [35]:
#Consider two random array A and B, check if they are equal : use allclose: Returns True if two arrays are element-wise equal within a tolerance.
A = np.random.randint(0,6,10)
B = np.random.randint(0,7,10)
equal = np.allclose(A,B)
print(equal)

False


In [36]:
A =[1,1,1,1,1,1]
B =[1,1,1,1,1,1]
equal = np.allclose(A,B)
print(equal)

True


In [38]:
#Checking both the shape and the element values, no tolerance (values have to be exactly equal)
A = np.random.randint(0,6,10)
B = np.random.randint(0,7,10)
equal = np.array_equal(A,B)
print(equal)

False


In [41]:
#Create random vector of size 10 and replace the maximum value by 0
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)
print(Z.argmin())

[0.03876887 0.41636947 0.60528818 0.75403222 0.31201159 0.09815701
 0.04187548 0.77689758 0.06354648 0.        ]
9


In [44]:
np.set_printoptions(threshold=float("inf"))
Z = np.random.random((5,5))
print(Z)

[[0.70281674 0.56610412 0.40386242 0.86211354 0.58653562]
 [0.02358973 0.46024303 0.47485781 0.42364426 0.40843542]
 [0.32975811 0.74880054 0.35599886 0.57449628 0.46208456]
 [0.09555316 0.8315052  0.23383003 0.07932242 0.13982268]
 [0.32915411 0.84697645 0.44468806 0.47163651 0.64421189]]


In [45]:
from io import StringIO

# Fake file
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


In [49]:
#What is the equivalent of enumerate for numpy arrays?
z = np.arange(9).reshape(3,3)
for i, v in np.ndenumerate(z):
  print(i,v)
for i in np.ndindex(z.shape):
  print(i,z[i])


(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
